added basic elements and functionality for login
Pelani2/trello-clone pull request #15
Opened 2023-08-02 09:57 UTC by Pelani2

2023-08-03 21:51 UTC, mitar-djakovic requested changes

2023-08-03 21:51 UTC, mitar-djakovic commented on src/pages/Login/index.js
> +import Button from "../../components/Button";
Svaki Index fajl moras da preimenujes u index.js, iz nekog razloga mi puca aplikacija

2023-08-03 21:51 UTC, mitar-djakovic commented on package.json
> +    "formik": "^2.4.2",
zasto si instalirao formik? Kad si koristio react-hook-froms?

2023-08-03 21:51 UTC, mitar-djakovic commented on src/pages/PasswordReset/index.js
> +import React from "react";
Obrisi ovu stranu, ona nije deo ovog taska

2023-08-04 09:25 UTC, Pelani2 commented on src/pages/Login/index.js
> +import Button from "../../components/Button";
eo

2023-08-04 09:26 UTC, Pelani2 commented on package.json
> +    "formik": "^2.4.2",
sam procitao negde da je jednostavniji i stabilniji od rhf pa reko da probam

2023-08-04 12:40 UTC, mitar-djakovic requested changes

2023-08-04 12:40 UTC, mitar-djakovic commented on package.json
> +    "formik": "^2.4.2",
Nije to bas istina, oba su stabilna i jednostavna, samo sto ti ne koristis sve iz react-hook-form da bi ti bio jednostavniji. Takodje react-hook-forms je mnogo optimizovaniji dok se koristi neko formik, zato ga i koristimo. Tako da obrisi formik za sad drzi se jednog paketa

2023-08-07 19:24 UTC, mitar-djakovic approved these changes

2023-08-07 20:17 UTC, merged